#!/bin/bash

echo "Installing plugins :"
for plugin in ${ES_PLUGINS[@]}; do
  echo " $plugin : "
  if /opt/elasticsearch/bin/plugin --install "$plugin"; then
    echo "OK"
  else
    echo "FAILED"
    exit 1
  fi
done

/opt/elasticsearch/bin/elasticsearch $@
